### ISSUE TITLE
"GLwidget object has no attribute image"

### ISSUE THREAD

**Issue by gacquier** [cazitouni/QgisGLViewer#6] opened 2023-07-20 10:40 UTC
Hello,

I try to use the extension on a colleague's PC and she gets an error "GLwidget object has no attribute image" whenever she clicks on a picture.

We both have QGIS 3.22 and use the same geopackage in the same project. The only differences I ses is 
- the Path for the pictures wich we adapted to fit for her configuration ==> We copy / pasted a path value in the explorer and it pointed correctly to the pictures
- the pictures are on onedrive, and donwloaded when we want to access to it ==> We tried to download some of them and it did not make any change. On my PC, it works fine even if the pictures are in the cloud.
Have you ever been confronted to this problem ?

**Comment by cazitouni** [comment] 2023-07-20 13:36
Hello @gacquier, 
Could you give me some path example and their value in the layer you try to use. 
Also since version 1.4 (the one in Qgis repo) it's possible to use relative path from the project. 
For example, if your qgis project is in a folder with another folder called "Images" just indicates "./images" in the path and it'll work.
Also this message is not very accurate I should modify it for the next version because sometimes the problem isnt really related to a path issue. 

Kind regards, Clément.

**Comment by gacquier** [comment] 2023-07-20 14:56
Hi, sure but I’m not sure it’s linked  with the path.

C:/Users/Iter Bonjour/ITER/BOH_MOA_Nom Eutde- Documents/BOH_Photos et illustrations/360\GSAA1087.JPG

I changed some values here to keep it somehow anonymous 😊.

Coult it be linked to an uncomplete QGIS install, like the last issue you solved ?

The new feature in 1.4 seems just great. I’ll try tomorrow to use relative path instead, just in case…

Thanks again for you precious time spent on this project !!!
Géraud


De : Clément Zitouni ***@***.***>
Envoyé : jeudi 20 juillet 2023 15:37
À : cazitouni/QgisGLViewer ***@***.***>
Cc : Géraud Acquier ***@***.***>; Mention ***@***.***>
Objet : Re: [cazitouni/QgisGLViewer] "GLwidget object has no attribute image" (Issue #6)


Hello @gacquier<https://github.com/gacquier>,
Could you give me some path example and their value in the layer you try to use.
Also since version 1.4 (the one in Qgis repo) it's possible to use relative path from the project.
For example, if your qgis project is in a folder with another folder called "Images" just indicates "./images" in the path and it'll work.
Also this message is not very accurate I should modify it for the next version because sometimes the problem isnt really related to a path issue.

Kind regards, Clément.

**Comment by cazitouni** [comment] 2023-07-20 17:40
It maybe related to the fact that your path got spaces in it or maybe that the path have mixed / and \ 
Could also be related to opengl, maybe try with the package I've linked [here](https://github.com/cazitouni/QgisGLViewer/issues/5#issuecomment-1519577004).
For relative path, the path should start with ./

for example in this project: 
![image](https://github.com/cazitouni/QgisGLViewer/assets/92778930/95aa37d5-d7ad-4a24-87ec-7309e7fdef3f)

path will be ./images/image_name.jpg

let me know if it helps, if not I will try to make a version with more debug infos.

**Comment by gacquier** [comment] 2023-07-21 10:19
Thanks again Clément !

I made a new install of QGIS via OSGeo4W and it worked. The last install probably did not include OpenGL…

We will try to use relative path. It will probably be of great help when different users work together 😊

Cheers,

Géraud

De : Clément Zitouni ***@***.***>
Envoyé : jeudi 20 juillet 2023 19:41
À : cazitouni/QgisGLViewer ***@***.***>
Cc : Géraud Acquier ***@***.***>; Mention ***@***.***>
Objet : Re: [cazitouni/QgisGLViewer] "GLwidget object has no attribute image" (Issue #6)


It maybe related to the fact that your path got spaces in it or maybe that the path have mixed / and \
Could also be related to opengl, maybe try with the package I've linked here<https://github.com/cazitouni/QgisGLViewer/issues/5#issuecomment-1519577004>.
For relative path, the path should start with ./

for example in this project:
[image]<https://user-images.githubusercontent.com/92778930/254963860-95aa37d5-d7ad-4a24-87ec-7309e7fdef3f.png>

path will be ./images/image_name.jpg

let me know if it helps, if not I will try to make a version with more debug infos.

**Comment by cazitouni** [comment] 2023-07-21 12:01
Hello @gacquier, 

Glad it worked for you, it happens to me once When I've upraded with osgeo4w.
It's also possible to install just the pyopengl package with osgeo4w during the package selection dialog. 

I close the issue.
Regards, Clement.

**Closed as completed by cazitouni** 2023-07-21 12:01 UTC
